baseurl = "https://bendl.me/blog/"
title = "Ben Lancaster"
theme = "whiteplain"
languageCode = "en"

publishDir = "../blog"

# Disqus shortname
disqusShortname = "http-bendl-me-blog"
# google analytics tracking id
googleAnalytics = "UA-114668070-3"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 Ben Lancaster"
pygmentsUseClasses=true
pygmentsStyle = "perldoc"

[params]
  # Date format
  #dateFormat = "January 2, 2006"
  
[permalinks]
  #posts = "/:year/:month/:title/"

# This is displayer in About page.
[params.author]
  name = "Ben Lancaster"
  # Gravatar or Abatar image
  gravatar = "bdl@live.co.uk"
  #avatar = "/path/to/avatar"

  twitter = "benl_"
  #facebook = "Facebook username"
  #googleplus = "Googleplus username"
  #instagram = "Instagram username"
  #tumblr = "Tumblr username"
  #flickr = "Flickr username"
  #reddit = "Reddit username"
  linkedin = "bendl"
  #slideshare = "Slideshare username"
  github = "bendl"
  #gitlab = "Gitlab username"
  #bitbucket = "Bitbucket username"
  #stackoverflow = "Stackoverflow username"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"
  #deviantart = "Deviantart username"
  #behance = "Behance username"
  #dribbble = "Dribbble username"
  #wordpress = "Wordpress username"
  #medium = "Medium username"
  #foursquare = "Foursquare username"
  #xing = "Xing username"
  #quora = "Quora username"
  #youtube = "Youtube username"
  #vimeo = "Vimeo username"
  #whatsapp = "Whatsapp username"
  #skype = "Skype username"
  #snapchat = "Snapchat username"
  #pinterest = "Pinterest username"
  #telegram = "Telegram username"
  #vine = "Vine username"
  email = "ben@bendl.me"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 20
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 30
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 40

#[[menu.main]]
#  name = "About"
#  identifier = "about"
#  url = "/about/"
#  weight = 50

# Footer Menu
#[[menu.footer]]
#  name = "About"
#  weight = 1
#  identifier = "about"
#  url = "/about/"